---
title: "NEVS descriptives"
author: "Albert Ward"
date: "6 Jun 2022"
output:
  html_document:
    toc: true # Table of contents
    toc_float: true # Floating table of contents
    theme: spacelab # options, in order: spacelab, readable, paper, cosmo
    highlight: textmate # options: textmate # Specifies the coloring style to be used in highlighted source code
    # df_print: paged # Printing data tables
editor_options: 
  chunk_output_type: inline
---

<style> body {text-align: justify} </style> <!-- Justify text. -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
# Packages

library(tidyverse)
library(tidymodels)
library(tidytext)
library(pscl)
library(dplyr)
library(MASS)
library(devtools)
library(styler)

# Plotting.
library(ggplot2)
library(ggeffects)
library(jtools)
library(plotly)
library(sjPlot)
library(ggrepel)

# For displaying model tables.
library(modelsummary)
```

```{r}
# Set the ggplot theme.

theme_set(
  theme_minimal() +
    theme(
      plot.title = element_text(face = "bold", size = 14, margin = margin(t = 0, r = 0, b = 20, l = 0)),
      plot.title.position = "plot",
      axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
      axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)),
      panel.grid.minor = element_blank()
    )
)
```

```{r}
# Import

nev <- read.csv("Local election results and NEVS.csv")

seats <- read.csv("NEV seat projection 2022.csv")

nat <- read.csv("NEVS and nat election results.csv")

```

```{r}
# Plotting NEVS

plot1 <- ggplot(nev, aes(x = Year)) +
  geom_line(aes(y = conNEV), color = "#3c6ac8") +
  geom_line(aes(y = labNEV), color = "#e04d51") +
  geom_line(aes(y = ldNEV), color = "#ebb036") +
  geom_line(aes(y = ukipNEV), color = "#79349d") +
  # geom_vline(xintercept = 1979, linetype = "longdash") +
  # geom_vline(xintercept = 1997, linetype = "longdash") +
  # geom_vline(xintercept = 2010, linetype = "longdash") +
  labs(
    y = "National equivalent vote share",
    title = "National equivalent vote share (NEVS) by party",
    subtitle = "Changes of gov't indicated"
  ) +
  theme(
    plot.title = element_text(face = "bold", margin = margin(t = 0, r = 0, b = 0, l = 0)),
    plot.subtitle = element_text(size = 12, margin = margin(t = 10, r = 0, b = 20, l = 0)),
    axis.title.y = element_text(size = 12),
    axis.title.x = element_blank(),
    axis.text = element_text(size = 12),
    legend.position = "none"
  )

plot1 +
  annotate(geom = "text", x = 1980, y = 50, label = "1979", hjust = "left", size = 4.25, fontface = 2) +
  annotate(geom = "text", x = 1998, y = 50, label = "1997", hjust = "left", size = 4.25, fontface = 2) +
  annotate(geom = "text", x = 2011, y = 50, label = "2010", hjust = "left", size = 4.25, fontface = 2) +
  annotate("segment", x = 1979, xend = 1979, y = 60, yend = 0, linetype = "solid", alpha = 0.75) +
  annotate("segment", x = 1997, xend = 1997, y = 60, yend = 0, linetype = "solid", alpha = 0.75) +
  annotate("segment", x = 2010, xend = 2010, y = 60, yend = 0, linetype = "solid", alpha = 0.75) +
  annotate("rect", xmin = 1992, xmax = 1997, ymin = 0, ymax = 60, alpha = .1) +
  annotate("rect", xmin = 1974, xmax = 1979, ymin = 0, ymax = 60, alpha = .1) +
  annotate("rect", xmin = 2005, xmax = 2010, ymin = 0, ymax = 60, alpha = .1) +
  annotate(geom = "text", x = 2018, y = 26.5, label = "Labour", hjust = "left", size = 4.25, fontface = 1, color = "#e04d51") +
  annotate(geom = "text", x = 2015, y = 44, label = "Conservatives", hjust = "left", size = 4.25, fontface = 1, color = "#3c6ac8") +
  annotate(geom = "text", x = 2017, y = 21, label = "Lib Dems", hjust = "left", size = 4.25, fontface = 1, color = "#ebb036") +
  annotate(geom = "text", x = 2018, y = 8, label = "UKIP", hjust = "left", size = 4.25, fontface = 1, color = "#79349d")
```

```{r}
# Seat projections

ggplot(seats, aes(x = party, y = seats, fill = party)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  # geom_text(aes(label = seats), vjust = 1.8, color = "white", fontface = "bold", size = 5) +
  ylab("Projected seats in Parliament") +
  ggtitle("Projected seats in Parliament using NEVS, 2022 local elections") +
  theme(
    plot.title = element_text(face = "bold", margin = margin(t = 0, r = 0, b = 30, l = 0)),
    axis.title.y = element_text(size = 14),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 12),
    axis.text.x = element_text(size = 14, face = "bold"),
    plot.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "none",
    aspect.ratio = 1.5/2
  ) +
  scale_fill_manual(values = c("#3c6ac8", "#e04d51", "#ebb036")) +
  scale_x_discrete(labels = c("Conservatives", "Labour", "Lib Dems")) +
  annotate(geom = "text", x = 0.83, y = 215, label = "  262 \n(-103)", hjust = "left", size = 5, fontface = 2, colour = "White") +
  annotate(geom = "text", x = 1.86, y = 240, label = " 287 \n(+84)", hjust = "left", size = 5, fontface = 2, colour = "White") +
  annotate(geom = "text", x = 2.87, y = 65, label = "  23 \n(+12)", hjust = "left", size = 5, fontface = 2, colour = "Black")
```

```{r}
# Scatter

# Labour
ggplot(nat, aes(x = lableadNEV, y = lableadnGE, color = Year)) +
  geom_point(colour = "black", alpha = 1) +
  geom_smooth(method = lm, colour = "black") +
  labs(x = "Labour lead over Con in local election (NEVS)", y = "Labour lead over Con at next GE",
       subtitle = "Points indicate local elections"
       ) +
  ggtitle("Relationship between local and general election success for Labour") +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  scale_x_continuous(labels = scales::percent_format(scale = 1)) +
  scale_color_gradient(low = "#1d0101", high = "#ff3939") +
  geom_text_repel(
    aes(label = Year),
    size = 4, box.padding = unit(0.37, "lines")
  ) +
  theme(
    plot.subtitle = element_text(size = 12, margin = margin(t = -10, r = 0, b = 10, l = 0)),
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12)
  )

# Con
ggplot(nat, aes(x = conleadNEV, y = conleadnGE, color = Year)) +
  geom_point(colour = "black", alpha = 1) +
  geom_smooth(method = lm, colour = "black") +
  labs(x = "Con lead over Labour in local election (NEVS)", y = "Con lead over Labour at next GE",
       subtitle = "Points indicate local elections"
       ) +
  ggtitle("Relationship between local and general election success for Conservatives") +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  scale_x_continuous(labels = scales::percent_format(scale = 1)) +
  geom_text_repel(
    aes(label = Year),
    size = 4, box.padding = unit(0.37, "lines")
  ) +
  theme(
    plot.subtitle = element_text(size = 12, margin = margin(t = -10, r = 0, b = 10, l = 0)),
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12)
  )
```
